### ISSUE TITLE
Add .serverless to the gitignore.

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/serverless-express#1]
Currently the project is shipping all of it's cloudformation in the serverless folder. This folder should be ignored by version control and removed from the current project.

1. Delete the .serverless folder and commit it.
2. Add `.serverless` to the .gitignore

**Comment by BlakeGuilloud** [comment]
@drtonton is going to take this on

**Comment by ghost** [comment]
:'( to late!
